compatibility_flags = [ "nodejs_compat_v2" ]
name = 'clerk-astro-cf-quickstart'
main = "./dist/_worker.js/index.js"
compatibility_date = "2025-08-15"

[assets]
binding = "ASSETS"
directory = "./dist"

[observability]
enabled = true

[vars]
PUBLIC_CLERK_PUBLISHABLE_KEY = "pk_test_ZXRlcm5hbC1zdW5maXNoLTIyLmNsZXJrLmFjY291bnRzLmRldiQ"
PUBLIC_CLERK_SIGN_IN_FORCE_REDIRECT_URL= "/protected"
PUBLIC_CLERK_SIGN_IN_URL="/sign-in"
PUBLIC_CLERK_SIGN_UP_URL="/sign-up"
